### PR TITLE
[MSTAGE-24] - set minimum maven version to 3.1

### PR DESCRIPTION
**Pull request by michaelboyles**
https://issues.apache.org/jira/browse/MSTAGE-24

### CODE REVIEW

**Review by elharo — COMMENTED** [review]
running jenkins 
https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven-stage-plugin/job/2/

**Comment by elharo** [comment]
Tests failed. :-(

**Comment by michaelboyles** [comment]
Ah, maven-artifact-manager has been discontinued for Maven 3. I replaced it with maven-compat which seems like the right thing to do. Let me know if it's not

**Review by elharo — COMMENTED** [review]
Possibly as an interim step. However, the maven-compat docs says "Maven2 classes maintained as compatibility layer for plugins that need to keep Maven2 compatibility.

Plugins should avoid these classes and be updated to use only Maven3 dependencies (and require Maven3): see Plugin migration to Maven3 dependencies documentation to get hints on how to make the update."

**Comment by michaelboyles** [comment]
Problem is this plugin has no tests, except 1 which is ignored, so I'm hesitant to make any more changes than I have to.

Suggest we raise a new jira to fix and enable the test, which will also mean we can fix close and [MSTAGE-20](https://issues.apache.org/jira/browse/MSTAGE-20)

**Review by elharo — COMMENTED** [review]
Oh damn, I didn't notice that. Fixing that is job #1 then. We shouldn't merge anything else, this PR included, until we have that working. :-(

**Pull request closed without merging**
